branches:
  only:
    - master
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
environment:
  nodejs_version: "11"
init:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yarn
install:
  - node --version
  - npm --version
  - yarn --version
  - yarn
build: off
