sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - node_modules

jobs:
  include:
  - stage: lint
    language: node_js
    node_js: 10
    install:
      - travis_retry yarn
      - travis_retry yarn global add @commitlint/travis-cli
    script:
      - commitlint-travis
      - yarn lint
      - pushd packages/cordova-plugin-admob-suite
      - yarn prepare
      - popd
      - pushd examples/ionic-angular
      # - yarn build
      - yarn lint
      - popd
  - stage: test
    env: PLATFORM=ios-11.4
    os: osx
    osx_image: xcode9.4
  - env:
      - PLATFORM=android-8.0
      - ANDROID_ABI=x86_64
      - ANDROID_API_LEVEL=28
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools # required to get the newest Android SDK tools.
        - build-tools-$ANDROID_API_LEVEL
        - android-$ANDROID_API_LEVEL
        - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
  - env:
      - PLATFORM=android-5.1
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=22
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools
        - build-tools-26.0.2
        - android-$ANDROID_API_LEVEL
        - android-$ANDROID_API_LEVEL
        - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
  - env:
      - PLATFORM=android-4.4
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=19
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools
        - build-tools-27.0.3
        - android-$ANDROID_API_LEVEL
        - android-$ANDROID_API_LEVEL
        - sys-img-$ANDROID_ABI-android-$ANDROID_API_LEVEL
  - stage: deploy
    if: branch = master AND type != pull_request
    language: node_js
    node_js: 10
    after_success:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - pushd website
      - travis_retry yarn
      - GIT_USER="${GH_NAME}" yarn publish-gh-pages
      - popd

before_install:
  - nvm install 10
  - travis_retry curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version
  - if [[ "$PLATFORM" =~ android ]]; then android list sdk --extended --no-ui --all; fi
  - if [[ "$PLATFORM" =~ android ]]; then android list targets; fi

install:
  - travis_retry yarn
  - if [[ "$PLATFORM" =~ android ]]; then echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI; fi

script:
  - yarn test
  - if [[ "$PLATFORM" =~ android ]]; then yarn test-android; fi
  - if [[ "$PLATFORM" =~ ios ]]; then yarn test-ios; fi
  - if [[ "$PLATFORM" =~ ios ]]; then pushd packages/cordova-plugin-admob-suite/src/ios && swiftlint && popd; fi
