sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  yarn: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - node_modules

matrix:
  include:
  - env: PLATFORM=ios-11.4
    os: osx
    osx_image: xcode9.4
  - env:
      - PLATFORM=android-8.0
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=26
    language: android
    android:
      components:
        - tools
        - platform-tools
        - tools # required to get the newest Android SDK tools.
        - build-tools-26.0.2
        - android-26
        - sys-img-armeabi-v7a-android-26
  - env:
      - PLATFORM=android-5.1
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=22
    language: android
  - env:
      - PLATFORM=android-4.4
      - ANDROID_ABI=armeabi-v7a
      - ANDROID_API_LEVEL=19
    language: android
    android:
        components:
            - tools
            - platform-tools
            - tools
            - build-tools-27.0.3
            - android-16
            - android-$ANDROID_API_LEVEL
            - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [[ "$PLATFORM" =~ android ]]; then android list targets; fi

install:
  - yarn
  - yarn global add @commitlint/travis-cli
  - if [[ "$PLATFORM" =~ android ]]; then echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI; fi

script:
  - commitlint-travis
  - yarn test
  - if [[ "$PLATFORM" =~ android ]]; then yarn test-android; fi
  - if [[ "$PLATFORM" =~ ios ]]; then yarn test-ios --build-only; fi
