sudo: false

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
  - env: PLATFORM=ios-11.4
    os: osx
    osx_image: xcode9.4
  - language: android
    android:
      components:
        - tools
        - platform-tools
        - tools # required to get the newest Android SDK tools.
        - build-tools-26.0.2
        - android-26

before_install:
  - nvm install 10
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn
  - yarn global add @commitlint/travis-cli

script:
  - commitlint-travis
